### ISSUE TITLE
How to open the menu and change configurations.

### ISSUE THREAD

**Issue by pil0lo** [TheAnsuz/Lethal-Company-Configurable-Company-API#14]
I don't see it in the list.
Where can I change it?

![1](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/143984023/4c144f2d-0b02-4366-95a2-d0920eb51bdb)
![2](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/143984023/454c9c64-d658-4392-8910-5842b22fb40f)

**Comment by TheAnsuz** [comment]
Hello @pil0lo 

You can check the menu after clicking the **first** button, right away where you can select a file slot and change the server name. There will be a button at the top left of the screen, if you click it, the menu will open.

This is due to the functionallity of the mod, being able to have different settings for each save file.

Hope this helps :)

**Comment by pil0lo** [comment]
thank you
Is it possible to set the timer to be visible even indoors?

**Comment by pil0lo** [comment]
thank you
Is it possible to set the timer to be visible even indoors?

**Comment by TheAnsuz** [comment]
The mod does not currently provide that option but I can add it as a suggestion for later releases. You can submit your own suggestions by commenting on [The suggestions excel](https://docs.google.com/spreadsheets/d/1b-4zDakbTEjvyTS-qmPLkjE4tKIJpX6CDYSbLuKvM0Q/edit?usp=sharing).

I will mark the question as closed, if you have any other question/issue, feel free to reopen it or create a new one.

Thanks for using the mod!
