### ISSUE TITLE
[Conflict] LC_VR incompatible

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#15]
https://github.com/DaXcess/LCVR/issues/233

**Comment by TheAnsuz** [comment]
Hey @CoolLKKPS 

Im sorry but that issue does not seem to provide any info related to Configurable company nor Lethal company variables (The logs are not related to the mentioned mods), Is this issue happening while only having LCV and LC_VR installed?

Also for the issue you submited on the other github, I suggest to insist to the developer to give you some information about the logs, they are for sure logs about LCVR.Plugin.VerifyGameVersion() method failing but the information he provides, there is no way to modify the Assembly.Location (that I am aware of) and LCV/CC does not change anything related to it.

I would love to help but I have no information on this issue, pleasle comunicate with the developer of VR to give you some feedback so I can check out the root of the issue.

Thanks in advance!

**Comment by CoolLKKPS** [comment]
probably not now bc i need to rest now, but will keep tracking this issue

**Comment by DaXcess** [comment]
The first encounter with a preload patcher mod :tada: 

Patching Assembly-CSharp.dll causes it to get loaded into the AppDomain in a different way than if it were to be loaded by Unity directly (e.g. Load instead of LoadFile), which causes the Assembly to have no file path associated with it.

This is easily fixed on my end by using `Paths.ManagedPath` instead of `typeof(PlayerControllerB).Assembly.Location` as that is now confirmed to be unpredictable.

This has been fixed in DaXcess/LCVR@b5bc5a130548d9bf632f2c81d00df6f987ad245c

**Comment by TheAnsuz** [comment]
Hello @DaXcess good to hear you were able to solve it.

Seems a bit weird that Preloaders work that way but I guess BepInEx is built like that.
_(Correction: makes sense preloaders do that, that way the modification of the assembly does not affect the dll so modifications are volatile)_

Thank @CoolLKKPS for reporting the issue in both ends and @DaXcess for the fast response!
