### ISSUE TITLE
[FEATURE] Interior configuration

### ISSUE THREAD

**Issue by goofygoober719** [TheAnsuz/Lethal-Company-Configurable-Company-API#45]
By default, most moons in lethal company have rare chances of generating with the alternate interior style. I think it would be cool if there were options to change the likelihood of getting the alternate interior on each moon. 

Currently, you can tweak just about everything related to moon interiors, so I think being able to modify the chance of each interior layout would be a very welcome addition, especially with the possibility of new interiors being added in future updates.

**Comment by TheAnsuz** [comment]
Hello @goofygoober719 

This has been in my focus for at least 3 months, im slowly modifying the mod to not break stuff and to be able to implement this (due to how they are registered in game, there is no easy way to provide a user-frendly method to modify it) yet it is still something that is planned to be added in a future release of the mod!

The problem with this comes with compatibility issues with other mods and allowance of custom interiors to also work on every moon, same as enemies and moons.
