### ISSUE TITLE
[BUG] Scrap value multiplier

### ISSUE THREAD

**Issue by Ninja-Kappa** [TheAnsuz/Lethal-Company-Configurable-Company-API#53]
## **Describe the bug**
What happened that made you think something does not work as intended. A short description with something like *The menu does not open regardless of how many times I click*.

The scrap value multiplier per planet doesn't seem to work correctly. So far, it only seems to affect the value of the Apparatus.

## **How to reproduce the issue**
Try to explain what you did to reproduce the issue. If you down know what you did ir is unclear, leave it blank. For example *click host, go back and then click again*

I changed the scrap value multiplier for Embrion and Artifice to a very high setting and scrap values inside the maps are still the same as their default values.

## **Mods and profile**
It's very important that you write the version of the game and the version of Configurable Company or any related mods to the issue. Use the following line:
- Game version: v61
- Configurable company: v3.5.0

Profile code: my_profile_code

## **Extra information**
Anything else you want to add. If you have console logs, any error or screenshot, this is the ideal place, otehrwise, you can just leave it empty.

**Comment by TheAnsuz** [comment]
Hello @Ninja-Kappa 

I might need some additional information to be able to look into the issue, do you mind sharing your profile code to check the issue? I might also need your configuration settings which you could send as a screenshot or save within your profile using a preset in order to share it among your profile code.

*Keep in mind that there might be another mod modifying those values causing some compatiblity issue*

Thanks in advance!

**Comment by Ninja-Kappa** [comment]
Apologies for not providing it initially. Here is my profile code:

019181f4-0c7d-7c04-3716-fb023f052e68

It could very well be another mod that is conflicting with it. Thanks for looking into this.!

**Comment by TheAnsuz** [comment]
Hello @Ninja-Kappa 

This issue will be fixed with the latest update for LCV (2.6.0) wich will come in a few days.

Thanks for the report!
