### ISSUE TITLE
[QUESTION] tbh i don't think those error log are really important, can u lower those logs level?

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#78]
i did really care about the log that from error level, but after i read the information i don't think that deserve to use error level, those logs need to use warning level not error level, and less spaming

`When loading a save`
[Error  :Configurable Company Variables] [EnemyPool] Pooled enemy `RadMech` with more than one enemy registered `(size: 8)`. THIS WILL CAUSE ERRORS
[Error  :Configurable Company Variables] [EnemyPool] Pooled enemy `ButlerBees` with more than one enemy registered `(size: 2)`. THIS WILL CAUSE ERRORS
`When loading the world`
[Error  :Configurable Company Variables] [LevelScrapValue] > No configuration found for `AuralisLevel`

**Comment by TheAnsuz** [comment]
Hello @CoolLKKPS 

The reason those logs are at error level is because they should not be ignored, there are some failsafes to avoid fatal errors and big issues caused by these, however if you encounter these, some custom moons are creating enemies in an incorrect way and most likely will cause memory leaks/configurations not applying.

I can provide more information about when do this errors occur and how to prevent them but I can't say for sure what custom moon is causing them.

If you feel that even after those errors configurations work propertly yea, you can pretty much ignore them.
